### PR TITLE
RF: remove datalad_deprecated dependency

### PR DESCRIPTION
**Pull request by yarikoptic**
Was introduced in https://github.com/datalad/datalad-crawler/pull/94
with only hypothetical assumptions of the necessity.  We are now hypothesizing
that it was not needed

### CODE REVIEW

**Comment by yarikoptic** [comment]
it wasn't hypothetical -- it was indeed due to use of `ls`:

```
______ ERROR collecting datalad_crawler/pipelines/tests/test_openfmri.py _______
ImportError while importing test module '/home/travis/build/datalad/datalad-crawler/datalad_crawler/pipelines/tests/test_openfmri.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../virtualenv/python3.7.1/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
datalad_crawler/pipelines/tests/test_openfmri.py:61: in <module>
    from .. import openfmri
datalad_crawler/pipelines/openfmri.py:29: in <module>
    from datalad.api import ls
E   ImportError: cannot import name 'ls' from 'datalad.api' (/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/datalad/api.py)
_ ERROR collecting datalad_crawler/pipelines/tests/test_openfmri_collection.py _
ImportError while importing test module '/home/travis/build/datalad/datalad-crawler/datalad_crawler/pipelines/tests/test_openfmri_collection.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../virtualenv/python3.7.1/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
datalad_crawler/pipelines/tests/test_openfmri_collection.py:37: in <module>
    from ..openfmri import superdataset_pipeline as ofcpipeline
datalad_crawler/pipelines/openfmri.py:29: in <module>
    from datalad.api import ls
E   ImportError: cannot import name 'ls' from 'datalad.api' (/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/datalad/api.py)
________ ERROR collecting datalad_crawler/pipelines/tests/test_xnat.py _________
ImportError while importing test module '/home/travis/build/datalad/datalad-crawler/datalad_crawler/pipelines/tests/test_xnat.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../virtualenv/python3.7.1/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
datalad_crawler/pipelines/tests/test_xnat.py:56: in <module>
    from ..xnat import XNATServer
datalad_crawler/pipelines/xnat.py:43: in <module>
    from datalad.api import ls
E   ImportError: cannot import name 'ls' from 'datalad.api' (/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/datalad/api.py)
=========================== short test summary info ============================
ERROR datalad_crawler/pipelines/tests/test_openfmri.py
ERROR datalad_crawler/pipelines/tests/test_openfmri_collection.py
ERROR datalad_crawler/pipelines/tests/test_xnat.py
!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!
```
fixing that

**Comment by yarikoptic** [comment]
green is good.
